#!/bin/sh

npx --no -- commitlint --edit $1

if [ $? -ne 0 ]; then
    echo ""
    echo "Commit rejected!"
    echo "Please follow the commit message format:"
    echo "   <type>/<scope>: <message>"
    echo ""
    echo "Allowed types: feat | fix | refactor | chore | docs | style | test"
    exit 1
fi
