#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Lint code
echo "Running ESLint..."
yarn run lint
if [ $? -ne 0 ]; then
    echo "❌ Lint failed! Commit aborted."
    exit 1
fi

# Run unit tests
# echo "🧪 Running tests..."
# npm test
# if [ $? -ne 0 ]; then
#     echo "❌ Tests failed! Commit aborted."
#     exit 1
# fi
